### ISSUE TITLE
Cannot build CustomXMLSerializer with Mono

### ISSUE THREAD

**Issue by alexchandel** [DanWBR/dwsim4#1]
Currently DWSIM cannot be built at all, since the `DWSIM.XMLSerializer` project in `CustomXMLSerializer` is in VB and uses Linq, which Mono does not support. Could you change this to C# or replace it with a normal XML Serializer?

**Comment by alexchandel** [comment]
@DanWBR I attempted to rewrite `DWSIM.XMLSerializer` in C#, [available here](http://pastebin.com/RRkqQY0B), would you please test it and merge it?

**Comment by DanWBR** [comment]
Mono doesn't support VB.NET version 9.0. Even if XMSerializer gets converted, we'd need to convert everything else.
